-- MySQL Script generated by MySQL Workbench
-- 11/09/14 23:37:35
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema houseMate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `houseMate` DEFAULT CHARACTER SET utf8 ;
USE `houseMate` ;

-- -----------------------------------------------------
-- Table `houseMate`.`house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`house` (
  `PK_houseID` INT(11) NOT NULL AUTO_INCREMENT,
  `houseName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `postcode` INT(11) NULL DEFAULT NULL,
  `state` VARCHAR(20) NULL DEFAULT NULL,
  `wifiPass` VARCHAR(45) NULL DEFAULT NULL,
  `binNight` VARCHAR(10) NULL DEFAULT NULL,
  `recycOrGreen` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_houseID`),
  UNIQUE INDEX `PK_houseID_UNIQUE` (`PK_houseID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `houseMate`.`chores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`chores` (
  `PK_choreID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_houseID` INT(11) NULL DEFAULT NULL,
  `choreName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_choreID`),
  INDEX `chore_to_house_idx` (`FK_houseID` ASC),
  CONSTRAINT `chore_to_house`
    FOREIGN KEY (`FK_houseID`)
    REFERENCES `houseMate`.`house` (`PK_houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `houseMate`.`my_aspnet_membership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`my_aspnet_membership` (
  `userId` INT(11) NOT NULL DEFAULT '0',
  `Email` VARCHAR(128) NULL DEFAULT NULL,
  `Comment` VARCHAR(255) NULL DEFAULT NULL,
  `Password` VARCHAR(128) NOT NULL,
  `PasswordKey` CHAR(32) NULL DEFAULT NULL,
  `PasswordFormat` TINYINT(4) NULL DEFAULT NULL,
  `PasswordQuestion` VARCHAR(255) NULL DEFAULT NULL,
  `PasswordAnswer` VARCHAR(255) NULL DEFAULT NULL,
  `IsApproved` TINYINT(1) NULL DEFAULT NULL,
  `LastActivityDate` DATETIME NULL DEFAULT NULL,
  `LastLoginDate` DATETIME NULL DEFAULT NULL,
  `LastPasswordChangedDate` DATETIME NULL DEFAULT NULL,
  `CreationDate` DATETIME NULL DEFAULT NULL,
  `IsLockedOut` TINYINT(1) NULL DEFAULT NULL,
  `LastLockedOutDate` DATETIME NULL DEFAULT NULL,
  `FailedPasswordAttemptCount` INT(10) UNSIGNED NULL DEFAULT NULL,
  `FailedPasswordAttemptWindowStart` DATETIME NULL DEFAULT NULL,
  `FailedPasswordAnswerAttemptCount` INT(10) UNSIGNED NULL DEFAULT NULL,
  `FailedPasswordAnswerAttemptWindowStart` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = '2';


-- -----------------------------------------------------
-- Table `houseMate`.`tenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`tenant` (
  `PK_tenantID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_houseID` INT(11) NOT NULL,
  `FK_aspMemberID` INT(11) NOT NULL,
  `isCurrent` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`PK_tenantID`),
  INDEX `FK_houseID_idx` (`FK_houseID` ASC),
  INDEX `memberConstraint_idx` (`FK_aspMemberID` ASC),
  CONSTRAINT `memberConstraint`
    FOREIGN KEY (`FK_aspMemberID`)
    REFERENCES `houseMate`.`my_aspnet_membership` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tenant_constraint`
    FOREIGN KEY (`FK_houseID`)
    REFERENCES `houseMate`.`house` (`PK_houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 63
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `houseMate`.`chore_allocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`chore_allocation` (
  `PK_allocationID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_choreID` INT(11) NOT NULL,
  `FK_tenantID` INT(11) NOT NULL,
  `dayOfWeek` VARCHAR(10) NULL DEFAULT NULL,
  `cycle` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_allocationID`),
  INDEX `allocation_to_chore_idx` (`FK_choreID` ASC),
  INDEX `allocation_to_tenant_idx` (`FK_tenantID` ASC),
  CONSTRAINT `allocation_to_chore`
    FOREIGN KEY (`FK_choreID`)
    REFERENCES `houseMate`.`chores` (`PK_choreID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `allocation_to_tenant`
    FOREIGN KEY (`FK_tenantID`)
    REFERENCES `houseMate`.`tenant` (`PK_tenantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `houseMate`.`house_bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`house_bill` (
  `PK_houseBillID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_houseID` INT(11) NOT NULL,
  `billType` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `dueDate` DATE NOT NULL,
  `paid?` TINYINT(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`PK_houseBillID`),
  INDEX `FK_houseID_idx` (`FK_houseID` ASC),
  CONSTRAINT `bill_constraint`
    FOREIGN KEY (`FK_houseID`)
    REFERENCES `houseMate`.`house` (`PK_houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `houseMate`.`individual_bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`individual_bills` (
  `PK_indivBillID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_houseBillID` INT(11) NOT NULL,
  `FK_tenantID` INT(11) NOT NULL,
  `splitAmount` DOUBLE NULL DEFAULT NULL,
  `datePaid` DATE NULL DEFAULT NULL,
  `recurring?` BINARY(1) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_indivBillID`),
  INDEX `individual_bill_constraint_idx` (`FK_houseBillID` ASC),
  INDEX `individual_tenant_constraint_idx` (`FK_tenantID` ASC),
  CONSTRAINT `individual_bill_constraint`
    FOREIGN KEY (`FK_houseBillID`)
    REFERENCES `houseMate`.`house_bill` (`PK_houseBillID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `individual_tenant_constraint`
    FOREIGN KEY (`FK_tenantID`)
    REFERENCES `houseMate`.`tenant` (`PK_tenantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 178
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `houseMate`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`list` (
  `PK_listID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_houseID` INT(11) NOT NULL,
  PRIMARY KEY (`PK_listID`),
  INDEX `houseID_idx` (`FK_houseID` ASC),
  CONSTRAINT `houseConstr`
    FOREIGN KEY (`FK_houseID`)
    REFERENCES `houseMate`.`house` (`PK_houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `houseMate`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`item` (
  `PK_itemID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_listID` INT(11) NOT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `category` VARCHAR(10) NULL DEFAULT 'food',
  `bought?` TINYINT(4) NULL DEFAULT '0',
  `description` VARCHAR(45) NULL DEFAULT '-',
  PRIMARY KEY (`PK_itemID`),
  INDEX `item_to_list_idx` (`FK_listID` ASC),
  CONSTRAINT `item to list`
    FOREIGN KEY (`FK_listID`)
    REFERENCES `houseMate`.`list` (`PK_listID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 165
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `houseMate`.`itemDescriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`itemDescriptions` (
  `PK_itemDescriptionsID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_itemID` INT(11) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PK_itemDescriptionsID`),
  INDEX `descConstr_idx` (`FK_itemID` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `houseMate`.`list_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`list_records` (
  `PK_recordID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_itemID` INT(11) NOT NULL,
  `FK_tenantID` INT(11) NOT NULL,
  `dateBought` DATE NOT NULL,
  PRIMARY KEY (`PK_recordID`),
  INDEX `item_to_record_idx` (`FK_itemID` ASC),
  INDEX `tenant_to_record_idx` (`FK_tenantID` ASC),
  CONSTRAINT `item_to_record`
    FOREIGN KEY (`FK_itemID`)
    REFERENCES `houseMate`.`item` (`PK_itemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tenant_to_record`
    FOREIGN KEY (`FK_tenantID`)
    REFERENCES `houseMate`.`tenant` (`PK_tenantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `houseMate`.`my_aspnet_applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`my_aspnet_applications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NULL DEFAULT NULL,
  `description` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `houseMate`.`my_aspnet_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`my_aspnet_profiles` (
  `userId` INT(11) NOT NULL,
  `valueindex` LONGTEXT NULL DEFAULT NULL,
  `stringdata` LONGTEXT NULL DEFAULT NULL,
  `binarydata` LONGBLOB NULL DEFAULT NULL,
  `lastUpdatedDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `houseMate`.`my_aspnet_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`my_aspnet_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `applicationId` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `houseMate`.`my_aspnet_schemaversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`my_aspnet_schemaversion` (
  `version` INT(11) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `houseMate`.`my_aspnet_sessioncleanup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`my_aspnet_sessioncleanup` (
  `LastRun` DATETIME NOT NULL,
  `IntervalMinutes` INT(11) NOT NULL,
  `ApplicationId` INT(11) NOT NULL,
  PRIMARY KEY (`ApplicationId`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `houseMate`.`my_aspnet_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`my_aspnet_sessions` (
  `SessionId` VARCHAR(191) NOT NULL,
  `ApplicationId` INT(11) NOT NULL,
  `Created` DATETIME NOT NULL,
  `Expires` DATETIME NOT NULL,
  `LockDate` DATETIME NOT NULL,
  `LockId` INT(11) NOT NULL,
  `Timeout` INT(11) NOT NULL,
  `Locked` TINYINT(1) NOT NULL,
  `SessionItems` LONGBLOB NULL DEFAULT NULL,
  `Flags` INT(11) NOT NULL,
  PRIMARY KEY (`SessionId`, `ApplicationId`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `houseMate`.`my_aspnet_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`my_aspnet_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `applicationId` INT(11) NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `isAnonymous` TINYINT(1) NOT NULL DEFAULT '1',
  `lastActivityDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `houseMate`.`my_aspnet_usersinroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`my_aspnet_usersinroles` (
  `userId` INT(11) NOT NULL DEFAULT '0',
  `roleId` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`userId`, `roleId`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `houseMate`.`notice_board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`notice_board` (
  `PK_noticeBoardID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_houseID` INT(11) NOT NULL,
  PRIMARY KEY (`PK_noticeBoardID`),
  INDEX `noticeboard_constraint_idx` (`FK_houseID` ASC),
  CONSTRAINT `noticeboard_constraint`
    FOREIGN KEY (`FK_houseID`)
    REFERENCES `houseMate`.`house` (`PK_houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `houseMate`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `houseMate`.`notice` (
  `PK_noticeID` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_noticeBoardID` INT(11) NOT NULL,
  `FK_tenantID` INT(11) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `message` VARCHAR(200) NOT NULL,
  `datePosted` DATETIME NOT NULL,
  `type` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`PK_noticeID`),
  INDEX `notice_constraint_idx` (`FK_noticeBoardID` ASC),
  INDEX `tenant-notice_constraint_idx` (`FK_tenantID` ASC),
  CONSTRAINT `notice_constraint`
    FOREIGN KEY (`FK_noticeBoardID`)
    REFERENCES `houseMate`.`notice_board` (`PK_noticeBoardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tenant-notice_constraint`
    FOREIGN KEY (`FK_tenantID`)
    REFERENCES `houseMate`.`tenant` (`PK_tenantID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 95
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
