//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMateService
{
    using System;
    using System.Collections.Generic;
    
    public partial class chore_allocation
    {
        public int PK_allocationID { get; set; }
        public int FK_choreID { get; set; }
        public int FK_tenantID { get; set; }
        public string dayOfWeek { get; set; }
        public Nullable<sbyte> cycle { get; set; }
    
        public virtual chore chore { get; set; }
        public virtual tenant tenant { get; set; }
    }
}
