//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMateService
{
    using System;
    using System.Collections.Generic;
    
    public partial class chore
    {
        public chore()
        {
            this.chore_allocation = new HashSet<chore_allocation>();
        }
    
        public int PK_choreID { get; set; }
        public Nullable<int> FK_houseID { get; set; }
        public string choreName { get; set; }
    
        public virtual ICollection<chore_allocation> chore_allocation { get; set; }
        public virtual house house { get; set; }
    }
}
