//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMateService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class houseMateEntities : DbContext
    {
        public houseMateEntities()
            : base("name=houseMateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<chore_allocation> chore_allocation { get; set; }
        public DbSet<chore> chores { get; set; }
        public DbSet<house> houses { get; set; }
        public DbSet<house_bill> house_bill { get; set; }
        public DbSet<individual_bills> individual_bills { get; set; }
        public DbSet<item> items { get; set; }
        public DbSet<list> lists { get; set; }
        public DbSet<list_records> list_records { get; set; }
        public DbSet<notice> notices { get; set; }
        public DbSet<notice_board> notice_board { get; set; }
        public DbSet<tenant> tenants { get; set; }
    }
}
