//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMateService
{
    using System;
    using System.Collections.Generic;
    
    public partial class house
    {
        public house()
        {
            this.chores = new HashSet<chore>();
            this.house_bill = new HashSet<house_bill>();
            this.lists = new HashSet<list>();
            this.notice_board = new HashSet<notice_board>();
            this.tenants = new HashSet<tenant>();
        }
    
        public int PK_houseID { get; set; }
        public string houseName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> postcode { get; set; }
        public string state { get; set; }
        public string password { get; set; }
        public string wifiPass { get; set; }
        public string binNight { get; set; }
        public Nullable<sbyte> recycOrGreen { get; set; }
    
        public virtual ICollection<chore> chores { get; set; }
        public virtual ICollection<house_bill> house_bill { get; set; }
        public virtual ICollection<list> lists { get; set; }
        public virtual ICollection<notice_board> notice_board { get; set; }
        public virtual ICollection<tenant> tenants { get; set; }
    }
}
