//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMateService
{
    using System;
    using System.Collections.Generic;
    
    public partial class house_bill
    {
        public house_bill()
        {
            this.individual_bills = new HashSet<individual_bills>();
        }
    
        public int PK_houseBillID { get; set; }
        public int FK_houseID { get; set; }
        public string billType { get; set; }
        public double amount { get; set; }
        public System.DateTime dueDate { get; set; }
        public sbyte paid_ { get; set; }
    
        public virtual house house { get; set; }
        public virtual ICollection<individual_bills> individual_bills { get; set; }
    }
}
