//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMateService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class houseMateEntities01 : DbContext
    {
        public houseMateEntities01()
            : base("name=houseMateEntities01")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<chore_allocation> chore_allocation { get; set; }
        public DbSet<chore> chores { get; set; }
        public DbSet<house> houses { get; set; }
        public DbSet<house_bill> house_bill { get; set; }
        public DbSet<individual_bills> individual_bills { get; set; }
        public DbSet<item> items { get; set; }
        public DbSet<itemDescription> itemDescriptions { get; set; }
        public DbSet<list> lists { get; set; }
        public DbSet<list_records> list_records { get; set; }
        public DbSet<my_aspnet_applications> my_aspnet_applications { get; set; }
        public DbSet<my_aspnet_membership> my_aspnet_membership { get; set; }
        public DbSet<my_aspnet_profiles> my_aspnet_profiles { get; set; }
        public DbSet<my_aspnet_roles> my_aspnet_roles { get; set; }
        public DbSet<my_aspnet_sessioncleanup> my_aspnet_sessioncleanup { get; set; }
        public DbSet<my_aspnet_sessions> my_aspnet_sessions { get; set; }
        public DbSet<my_aspnet_users> my_aspnet_users { get; set; }
        public DbSet<my_aspnet_usersinroles> my_aspnet_usersinroles { get; set; }
        public DbSet<notice> notices { get; set; }
        public DbSet<notice_board> notice_board { get; set; }
        public DbSet<tenant> tenants { get; set; }
    }
}
