//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMateService
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.list_records = new HashSet<list_records>();
        }
    
        public int PK_itemID { get; set; }
        public int FK_listID { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public Nullable<sbyte> bought_ { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<list_records> list_records { get; set; }
        public virtual list list { get; set; }
    }
}
