//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMateService
{
    using System;
    using System.Collections.Generic;
    
    public partial class list_records
    {
        public int PK_recordID { get; set; }
        public int FK_itemID { get; set; }
        public int FK_tenantID { get; set; }
        public System.DateTime dateBought { get; set; }
    
        public virtual item item { get; set; }
        public virtual tenant tenant { get; set; }
    }
}
