//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseMateService
{
    using System;
    using System.Collections.Generic;
    
    public partial class list
    {
        public list()
        {
            this.items = new HashSet<item>();
        }
    
        public int PK_listID { get; set; }
        public int FK_houseID { get; set; }
    
        public virtual house house { get; set; }
        public virtual ICollection<item> items { get; set; }
    }
}
